---
- name: Create nproxy a network
  community.docker.docker_network:
    name: nproxy_default

- { include: portainer.yml}        
- { include: npm.yml}        
- { include: nginx.yml}        
- { include: watchtower.yml}        
- { include: update_firewall.yml, become: yes }        
