---
- name: Allow http
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow npm
  community.general.ufw:
    rule: allow
    port: '81'
    proto: tcp

- name: Allow portainer
  community.general.ufw:
    rule: allow
    port: '9000'
    proto: tcp 


