---
- name: Deploy watchtower
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_DEBUG: 'true'
      WATCHTOWER_INCLUDE_STOPPED: 'true'
      WATCHTOWER_RUN_ONCE: 'true'  