---
- name: install prerequisites
  ansible.builtin.apt:
    update_cache: yes
    name:
      - ufw

- name: Deny all incoming by default
  community.general.ufw:
    default: deny
    direction: incoming

- name: Allow all incoming by default
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp 

- name: Enable UFW
  community.general.ufw:
    state: enabled
