---
- name: install prerequisites
  ansible.builtin.apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gnupg-agent
      - software-properties-common
      - python3-pip  

- name: add apt-key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repo
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: sleep for 20 sec
  ansible.builtin.wait_for:
    wait_for:
      timeout: 20

- name: install docker 
  ansible.builtin.apt:
    update_cache: yes
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: add user to docker group
  ansible.builtin.user:
    name: "{{username}}"
    groups: docker
    append: yes

- name: install python docker sdk
  become_user: "{{username}}"
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose

- name: install tmux
  ansible.builtin.apt:
    name: tmux
    state: present

- name: Reboot the machine
  ansible.builtin.reboot:
    reboot_timeout: 350 
